<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>

</head>

<body>




  <script>

    /*
       MỘT SỐ TỪ TIẾNG ANH TRONG NGÀNH
              - Sync : Đồng bộ
              - Async : Bất đồng bộ
    
    
              */

    /*
        // ví dụ về bất đồng bộ
        function test() {
    
          // Sẽ phải chờ 2 giây
          setTimeout(function () {
            console.log('1');
          }, 2000);
    
          console.log('2');
          console.log('3');
        }
        test();
    
        */

    /////////////////////////////////////////////////////////////////////
    // có 3 cách xử lý bất đồng bộ , Call back , Promiese , sync await

    // Những cái ko đồng bộ như : setTimeout , setInterval , fetch , XMLHttpRequest
    ///////////////////////////////////////////////////////////////////////////////////////

    // Giải thích về function await
    // async function func1() {
    //   const promiese = asyncOperation();
    //   return await promiese;
    // }

    // async function func2() {
    //   const promiese = asyncOperation();
    //   return promiese;
    // }


    // Ví dụ
    function promiesedDivision(x, y) {
      if (y === 0) {
        return Promise.reject(new Error('Số chia không thể bằng 0 được'));
      } else {
        return Promise.resolve(x / y);
      }
    }

    /*
        // Sử dụng await
        async function divideWithAwait() {
          return await promiesedDivision(6, 2);
        }
    
    
        // Không sử dụng await
        async function divideWithOutAwait() {
          return promiesedDivision(6, 2);
        }
    
        async function run() {
          const rs = await divideWithOutAwait();
          console.log(`divideWithOutAwait::${rs}`);
        }
        // Kết quả của việc sử dụng hay khoog sử dụng await đều bằng nhau
        run();
        */

    // Vậy khác nhau chỗ nào ? Nên sử dụng try catch
    async function divideWithAwait() {
      try {
        return await promiesedDivision(6, 0);
      } catch (error){
        console.error(`Err`, error.message);
      }
    }

    async function divideWithOutAwait() {
      try {
        return  promiesedDivision(6,0);
      } catch (error){
        console.error(`Err`, error.message);
      }
    }


    async function run() {
      const rs = await divideWithOutAwait();
      console.log(`divideWithOutAwait::${rs}`);
    }
    run();

  </script>







</body>

</html>